name: Deploy Docs on Release

on:
  push:
    branches:
      - main
  release:
    types: [published]
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensures we have access to all branches

      - name: Get package version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up git config
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages

      - name: Create version folder if not exists
        run: |
          if [ ! -d "$PACKAGE_VERSION" ]; then
            mkdir $PACKAGE_VERSION
            git add $PACKAGE_VERSION
            git commit -m "Create folder for version $PACKAGE_VERSION"
          fi

      - name: Copy /docs to new folder
        run: |
          git checkout main -- docs/
          cp -r docs/* $PACKAGE_VERSION/
          git add $PACKAGE_VERSION
          git commit -m "Deploy docs for version $PACKAGE_VERSION" || echo "No changes to commit"
          git push origin gh-pages
